<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */

?>

<div data-block="minicart" class="minicart-wrapper">
    <button class="action cart-button" onclick="window.location.href='<?= $block->escapeUrl($block->getShoppingCartUrl()) ?>'"
       data-bind="scope: 'minicart_content'" >
        <i class="fa fa-shopping-cart fa-lg" aria-hidden="true"></i>

        <!-- ko if: getCartParam(summary_count') -->

        <span class="cart-counter" data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>

        <span class="cart-counter qty"><!-- ko text: getCartParam('summary_count') --><!-- /ko --><?php $counter = $this->helper('\Magento\Checkout\Helper\Cart');  echo $counter->getItemsCount();?></span>
        <!-- /ko -->

    </button>
    <?php if ($block->getIsNeedToDisplaySideBar()) :?>
        <div class="block block-minicart"
             data-role="dropdownDialog" 
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <?= $block->getChildHtml('minicart.addons') ?>
        </div>
    <?php else :?>
        <script>
            require(['jquery'], function ($) {
                $('a.action.showcart').click(function() {
                    $(document.body).trigger('processStart');
                });
            });
        </script>
    <?php endif ?>
    <script>
        window.checkout = <?= /* @noEscape */ $block->getSerializedConfig() ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?= $block->escapeJs(
            $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))
        ) ?>"
        }
    }
    </script>
</div>