<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_PartFinder
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<div class="select-attributes-block <?= /* @noEscape */ $block->getData('config/dataScope') ?>" data-role="select-products-step">
    <h2 class="steps-wizard-title"><?= $block->escapeHtml(
        __('Step 1: Select Products')
    ); ?></h2>
    <div class="selected-attributes" data-bind="scope: '<?= /* @noEscape */  $block->getComponentName() ?>'">
        <?= $block->escapeHtml(
            __('Selected Products:')
        ); ?>
        <span data-bind="text: selectedProducts() || '--'"></span>
    </div>
</div>
<?= $block->getChildHtml() ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "<?= /* @noEscape */  $block->getComponentName() ?>": {
                        "component": "Webkul_PartFinder/js/variations/steps/select_products",
                        "multiselectName": "<?= /* @noEscape */ $block->getData('config/multiselectName') ?>",
                        "providerName": "<?= /* @noEscape */ $block->getData('config/providerName') ?>",
                        "appendTo": "<?= /* @noEscape */  $block->getParentComponentName() ?>"
                    }
                }
            }
        }
    }
</script>
<script>
    require(['jquery'], function ($) {
        $('.<?= /* @noEscape */ $block->getData('config/dataScope') ?>[data-role=select-products-step]').applyBindings();
        $('body').trigger('contentUpdated');
    })
</script>
