<?php

function getCategorySelect(){

    $objectManager1 = \Magento\Framework\App\ObjectManager::getInstance();
    $categoryFactory = $objectManager1->create('Magento\Catalog\Helper\Category');
    $categoryManager = $objectManager1->create('Magento\Catalog\Model\CategoryRepository');
    $customerSession = $objectManager1->get('Magento\Customer\Model\Session');

    $categoryId = 831;  //Parent Category ID
    $subCategory = $objectManager1->create('Magento\Catalog\Model\Category')->load($categoryId);
    $categories = $subCategory->getChildrenCategories();

    $html = '<option value=\"0\">All Categories</option>';


    foreach ($categories as $id => $category) {

        $html .= "<option value=\"" .  $category->getId()  . "\">" . strtoupper($category->getName()) . "</option>";
        //echo '**** ' . $category->getId() . ' ****';
        if ($category->hasChildren()) {
            echo " **** HasChildren ****";

            $childrenMenus = $category->getChildrenCategories();
            foreach ($childrenMenus as $id => $childrenMenu) {
                $html .= "<option value=\"" .  $childrenMenu->getId()  . "\"> -- " . $childrenMenu->getName() . "</option>";
            }
        }
        /*        else
                {
                    $html .= "<option value=\"" .  $category->getId()  . "\">" . strtoupper($category->getName()) . "</option>";
                }
        */
    }
    return $html;
}


function getCategoryNav()
{
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $categoryFactory = $objectManager->create('Magento\Catalog\Helper\Category');
    $categoryManager = $objectManager->create('Magento\Catalog\Model\CategoryRepository');
    $customerSession = $objectManager->get('Magento\Customer\Model\Session');
    $categoryId = 831;  //Parent Category ID
    $subCategory = $objectManager->create('Magento\Catalog\Model\Category')->load($categoryId);
    $categories = $subCategory->getChildrenCategories();
    $sideMenuId = 491;
    //$sideMenuId = 43;
    $sideMenuSubCategory = $objectManager->create('Magento\Catalog\Model\Category')->load($sideMenuId);
    $sideMenuCategories = $sideMenuSubCategory->getChildrenCategories();
    $html = '    <div class="categories">';
    foreach ($categories as $id => $category) {
        //echo '**** ' . $category->getId() . ' ****';
        if ($category->hasChildren()) {
            $html .= '<div class="category-item">';
            $html .= '  <a class="category-item-link has-children" id="dropdown-' . $category->getId() . '" href="#" />' . $category->getName() . ' <i class="fas fa-caret-down ml-1"></i></a>';
            $html .= '  <div class="category-sub-menu" aria-labelledby="dropdown-' . $category->getId() . '">';
            $childrenMenus = $category->getChildrenCategories();
            foreach ($childrenMenus as $id => $childrenMenu) {
                //echo '  #### ' . $childrenMenu->getName() . '####';
                $html .= '<div class="sub-link-container">';
                $html .= '<a class="category-item-sub-link" href="' . $childrenMenu->getUrl() . '">' . $childrenMenu->getName() . '</a>';
                $subSubCategories = $childrenMenu->getChildrenCategories();
                foreach($subSubCategories as $id => $subSubCategory) {
                    $html .= '<a class="category-item-sub-sub-link" href="' . $subSubCategory->getUrl() . '">' . $subSubCategory->getName() . '</a>';
                }
                $html .= '  <a href="' . $childrenMenu->getUrl() . '" class="category-item-sub-sub-link view-more">View all<i class="fas fa-chevron-right ml-2"></i></a></div>';
            }
            $html .= ' <a class="main-view-more" href="' . $category->getUrl() . '">View all '. $category->getName() .'<i class="fas fa-chevron-right ml-2"></i></a>';
            $html .= '    </div>';
            $html .= "</div>";
        } else {
            $html .= '<div class="category-item">';
            $html .= '  <a class="category-item-link" href="' . $category->getUrl() . '" />' . $category->getName() . '</a>';
            $html .= '</div>';
        }
    }
    $html .= '    </div>';
    return $html;
}
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');

?>

<!-- 
<div class="top-contact-row contact-bar">
    <div class="container">
        <nav>
            <?php  echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('top_nav_bar_left')
                ->toHtml(); ?>
        </nav>

        <nav>
            <?php  echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('top_nav_bar_right')
                ->toHtml(); ?>
        </nav>
    </div>
</div>

<header class="main-nav">
    <div class="container">
        <div class="complete-nav">
            <div class="title-row">
                <div class="title-logo">
                    <a href="#" class="mobile-menu-toggle d-flex d-lg-none"><i class="fas fa-bars"></i></a>
                    <a class="" href="/">
                        <img src="/assets/images/midas/midas-logo-w-slogan.svg" class="site-logo" alt="midas logo" >
                    </a>
                </div>

                <div class="title-item-middle">
                    <div class="top-search-bar-container">
                        <form  action="/catalogsearch/result">
                            <div class="top-search-bar">
                                <div class="category-select category-search-item">
                                    <select>
                                        <?php echo getCategorySelect(); ?>
                                    </select>
                                </div>
                                <input class="search-bar-input" name="q" type="text" placeholder="Search" aria-label="Search">
                                <button class="search-bar-button"><i class="fas fa-search text-grey" aria-hidden="true"></i></button>
                            </div>
                        </form>
                        <div class="top-search-bar-mobile-backdrop">
                            <a href="#" class="mobile-search-close"><i class="fas fa-times"></i></a>
                        </div>
                    </div>

                </div>
                <div class="title-item">
                    <a href="#" class="mobile-search-toggle d-flex d-lg-none"><i class="fas fa-search"></i></a>
                    <a href="/parts-finder" class="mycar-button btn btn-primary d-none d-lg-flex"><i class="fas fa-cogs fa-lg" aria-hidden="true"></i>Parts Finder</a>
                    <button onclick="window.location.href='/wishlist';" class="favorite-button d-none d-lg-block"><i class="fa fa-heart fa-lg" aria-hidden="true"></i></button>
                    <button onclick="window.location.href='/checkout/cart'" class="cart-button">
                        <i class="fa fa-shopping-cart fa-lg" aria-hidden="true"></i>
                        <span class="cart-counter"><?php $counter = $this->helper('\Magento\Checkout\Helper\Cart');  echo $counter->getItemsCount();?></span>
                    </button>

            </div>
        </div>
    </div>
</header>

-->
<div class="main-menu-container ">
    <div class="container">

        <div class="main-menu--left">

            <div class="category-menu-container desktop">

                <div class="category-menu desktop">
                    <!--                    <a class="top-navbar-link category-menu-toggle" href="/">Home</a>-->
                    <?php echo getCategoryNav() ?>
                </div>
            </div>

        </div>
        <div class="main-menu--right">
            <?php  echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('bottom_navbar_right')
                ->toHtml(); ?>
        </div>
    </div>
</div>


<div class="category-menu-mobile">
    <div class="category-menu-mobile-content">
        <?php echo getCategoryNav() ?>
    </div>
    <div>
        <div class="mobile-menu bg-light">
            <?php  echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('mobile_menu_bottom_nav')
                ->toHtml(); ?>
        </div>
    </div>
    <div class="category-menu-mobile-backdrop">
        <a href="#" class="mobile-menu-close"><i class="fas fa-times"></i></a>
    </div>
</div>
