    <?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_PartFinder
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

//  @var \Webkul\PartFinder\Block\Widget\Partfinder $block
    ?>
<?php if ($block->getFinders()) :
    $filter = $block->getRequest()->getParam('finder', null);
    foreach ($block->getFinders() as $finder) :
        if (!$finder) {
            continue;
        }
        $dropdowns = $block->getDropdownOptions($finder->getId());
        if ($finder->getStatus()) :
            ?>
<div id="sidebar_finder_container_<?= $block->escapeHtml($finder->getId());?>" class="sidebar-finder-container" data-role="product-part-finder-widget">
    <div data-bind="scope: 'sidepartfinderOptions_<?= /* @noEscape */ $finder->getId() ?>'" class="part-finder-box">
        <div class="page-title-wrapper">
            <h1 class="finder-sidebar-title">
                <span class="base" data-ui-id="page-title-wrapper"><?= $block->escapeHtml($finder->getWidgetName()) ?></span>
            </h1>
        </div>
        <div class="content vertical">
            <form 
                id="finder_form_<?= $block->escapeHtml($finder->getId());?>" 
                class="finder-form" 
                method="GET" 
                data-bind="attr: {action: locationUrl}",
                data-mage-init='{"validation":{}}'
            >
                <fieldset class="fieldset" data-bind="foreach: dropdowns, sortableList: dropdowns">
                    <div class="field" data-bind="css: {required: is_required}">
                        <label class="label"><span data-bind="text:label"></span></label>
                        <div class="control">
                            <select data-bind="options: filterOptions,
                                optionsText: 'label',
                                optionsValue: 'option_id',
                                value: selected,
                                optionsCaption: 'Choose '+label+'...',
                                attr: {name: 'dropdown['+dropdown_id+']'},
                                css: {required: is_required}
                                "></select>
                        </div>
                    </div>
                </fieldset>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="button" data-bind="click: submitFinder" title="Submit" class="action submit primary">
                        <span><?= $block->escapeHtml(__('Search Parts')) ?></span>
                        </button>
                    </div>
                    <div class="primary">
                        <button type="button" data-bind="click: clearFinder" title="<?= $block->escapeHtml(__('Reset'))  ?>" class="action reset">
                            <span><?= $block->escapeHtml(__('Reset'))  ?></span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "sidepartfinderOptions_<?= /* @noEscape */  $finder->getId() ?>": {
                        "component": "Webkul_PartFinder/js/part-finder-widget",
                        "dropdowns": <?= /* @noEscape */ $block->jsonEncode($dropdowns) ?>,
                        "variations": <?= /* @noEscape */ $block->jsonEncode($block->getVariations($finder->getId())) ?>,
                        "url": "<?= /* @noEscape */ $block->getPagerUrl() ?>",
                        "params": "<?= /* @noEscape */ $filter ?>",
                        "form": "#finder_form_<?= $block->escapeHtml($finder->getId());?>"
                    }
                }
            }
        }
    }
</script>
<script>
    require(['jquery', 'mage/apply/main'], function ($, main) {
        main.apply();
    })
</script>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>