<li>
    <a class="d-none d-lg-inline-block ml-2" href="/midas-for-workshop"><span class="fas fa-building contact-row-nav-icon text-primary">&nbsp;</span>Midas for Workshop</a>
</li>
<li>
    <a class="d-none d-lg-inline-block ml-2" href="/fit-my-part"><span class="fas fa-tools contact-row-nav-icon text-primary">&nbsp;</span>Fit My Part </a>
</li>
<li>
    <a class="d-none d-lg-inline-block ml-2" href="/contact"><span class="fa fa-envelope contact-row-nav-icon text-primary">&nbsp;</span>Contact Us</a>
</li>