<li>
    <a href="https://www.facebook.com/midassouthafrica/?ref=br_rs" target="_blank" rel="noopener"><span class="text-dark fab fa-facebook-square ml-2 mr-0" aria-hidden="true">&nbsp;</span></a>
</li>
<li>
    <a href="https://www.youtube.com/channel/UCeuY-sjTip8s3SAwqcd5-6A" target="_blank" rel="noopener"><span class="text-dark fab fa-youtube mr-0 ml-2" aria-hidden="true">&nbsp;</span></a></p>
</li>