<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_PartFinder
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
$productMatrix = [];
$attributes = [];
?>
<div class="<?= /* @noEscape */ $block->getData('config/dataScope') ?>" data-role="step-wizard-dialog" data-bind="scope: '<?= /* @noEscape */ $block->getForm() ?>.<?= /* @noEscape */ $block->getModal() ?>'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<div class="<?= /* @noEscape */ $block->getData('config/dataScope') ?>" id="finder-variations-matrix" data-role="finder-variations-matrix">
    <div data-bind="scope: 'partfinderVariations'"></div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "<?= /* @noEscape */ $block->getData('config/form') ?>.addProductModal": {
                        "component": "Webkul_PartFinder/js/components/modal-products",
                        "options": {"type": "slide", "title": "<?= $block->escapeHtml(__('Add Products Manually')) ?>"},
                        "formName": "<?= /* @noEscape */ $block->getForm() ?>",
                        "isTemplate": false,
                        "stepWizard": "<?= /* @noEscape */ $block->getData('config/nameStepWizard') ?>",
                        "children": {
                            "custom_wizard": {
                                "url": "<?= /* @noEscape */ $block->getUrl($block->getData('config/urlWizard')) ?>",
                                "component": "Magento_Ui/js/form/components/html"
                            }
                        }
                    },
                    "<?= /* @noEscape */ $block->getData('config/form') ?>.partfinderVariations": {
                        "component": "Webkul_PartFinder/js/variations/variations",
                        "provider": "<?= /* @noEscape */ $block->getProvider() ?>",
                        "dataScopeVariations": "variations",
                        "dataScopeAttributes": "data.attributes",
                        "dataScopeAttributeCodes": "data.attribute_codes",
                        "dataScopeAttributesData": "data.product.finder_dropdowns_data",
                        "formName": "<?= /* @noEscape */ $block->getForm() ?>",
                        "attributeSetHandler": "<?= /* @noEscape */ $block->getForm() ?>.configurable_attribute_set_handler_modal",
                        "wizardModalButtonName": "<?= /* @noEscape */ $block->getForm() ?>.configurable.configurable_products_button_set.create_configurable_products_button",
                        "wizardModalButtonTitle": "<?= $block->escapeHtml(__('Edit Configurations')) ?>",
                        "productAttributes": <?= /* @noEscape */ json_encode($attributes) ?>,
                        "productUrl": "<?= /* @noEscape */ $block->getUrl('catalog/product/edit', ['id' => '%id%']) ?>",
                        "variations": <?= /* @noEscape */ json_encode($productMatrix) ?>,
                        "attributeSetCreationUrl": "<?= /* @noEscape */ $block->getUrl('*/product_set/save') ?>"
                    }
                }
            }
        }
    }
</script>
<script>
    require(['jquery', 'mage/apply/main'], function ($, main) {
        main.apply();
        $('.<?= /* @noEscape */ $block->getData('config/dataScope') ?>[data-role=step-wizard-dialog]').applyBindings();
        $('.<?= /* @noEscape */ $block->getData('config/dataScope') ?>[data-role=finder-variations-matrix]').applyBindings();
    })
</script>
