<?php
/**
 * Copyright © CodeInfinity. All rights reserved.
 */
?>

<style>

    .footer-subscribe-row {
        background-color: grey;
        color: white;
        padding: 20px 100px 20px 100px;
    }


    .footer-subscribe-row {
        background-color: #232323;
        color: white;
        padding: 20px 100px 20px 100px;
        position: relative;
        font-size: 14px;
    }

    .footer-social-group{
        position:relative;
    }

    .footer-social-text{
        float:right;
        width:70%;
    }

    .footer-social-icon{
        float:right;
        width:10%;
        color: black;
    }


</style>


<div class="footer">

    <div class="row  footer-menu-row">
            <div class="container-fluid footer-menu-groups">
                <div class="col-3 footer-group">
                    <h3 class="menu-footer">About</h3>
                    <ul class="menu-footer list-group">
                        <li class="menu-footer list-group-item">About Midas</li>
                    </ul>
                </div> <!-- About -->
                <div class="col-3 footer-group"> <!-- Help -->
                    <h3>Help</h3>
                    <ul class="menu-footer list-group">
                        <li class="menu-footer list-group-item">Terms and Conditions</li>
                        <li class="menu-footer list-group-item">Payment Policy</li>
                        <li class="menu-footer list-group-item">Privacy Policy</li>
                        <li class="menu-footer list-group-item">Returns & Delivery Policy</li>
                        <li class="menu-footer list-group-item">Shipping</li>
                        <li class="menu-footer list-group-item">Store Pickup</li>
                        <li class="menu-footer list-group-item">Track Order</li>
                        <li class="menu-footer list-group-item">How-to Videos</li>
                    </ul>
                </div>
                <div class="col-3 footer-group"> <!-- Shop -->
                    <h3>Shop</h3>
                    <ul class="menu-footer list-group">
                        <li class="menu-footer list-group-item">Car Care</li>
                        <li class="menu-footer list-group-item">Outdoor</li>
                        <li class="menu-footer list-group-item">Tools</li>
                        <li class="menu-footer list-group-item">Trailer Accessories</li>
                        <li class="menu-footer list-group-item">Vehicle Accessories</li>
                        <li class="menu-footer list-group-item">Wheel Accessories</li>
                        <li class="menu-footer list-group-item">Workshop Equipment</li>
                    </ul>
                </div>
                <div class="col-3 footer-group"> <!-- Contact Us -->
                    <h3>Contact Us</h3>
                    <ul class="menu-footer list-group">
                        <li class="menu-footer list-group-item"><strong>Customer Care</strong></li>
                        <li class="menu-footer list-group-item">Tel: 086 036 7463 </li>
                        <li class="menu-footer list-group-item">Email: customercare@midas.co.za</li>
                    </ul>
                </div>
            </div>
    </div> <!-- row footer-menu-row -->

    <div class="row  footer-subscribe-row col-12">
        <div class="col-3">
            <h4>Subscribe to our Newsletter</h4>
            Get 10% off your first purchase!!
        </div>
        <div class="col-6">
            <form class="form-inline">
                <div class="form-group col-5">
                    <input type="text" class="form-control" id="inputEmailAddress" placeholder="Enter your email address">
                </div>
                <button type="submit" class="btn btn-primary mb-2">Subscribe</button>
            </form>
        </div>
        <div class="col-3 footer-social-group">

            <div class="footer-social-icon">
                <i class="fab fa-youtube-square fa-3x"></i>
            </div>            <div class="footer-social-icon">
                <i class="fab fa-facebook-square fa-3x      "></i>
            </div>            <div class="footer-social-icon">
                <i class="fab fa-twitter-square fa-3x"></i>
            </div>
            <div class="footer-social-text">
                Follow us
            </div>
        </div>
    </div> <!-- row footer-menu-row -->



</div> <!--footer-->


