<?php

function getCategorySelect(){

    $objectManager1 = \Magento\Framework\App\ObjectManager::getInstance();
    $categoryFactory = $objectManager1->create('Magento\Catalog\Helper\Category');
    $categoryManager = $objectManager1->create('Magento\Catalog\Model\CategoryRepository');
    $customerSession = $objectManager1->get('Magento\Customer\Model\Session');

    $categoryId = 831;  //Parent Category ID
    $subCategory = $objectManager1->create('Magento\Catalog\Model\Category')->load($categoryId);
    $categories = $subCategory->getChildrenCategories();

    $html = '<option value=\"0\">All Categories</option>';


    foreach ($categories as $id => $category) {

        $html .= "<option value=\"" .  $category->getId()  . "\">" . strtoupper($category->getName()) . "</option>";
        //echo '**** ' . $category->getId() . ' ****';
        if ($category->hasChildren()) {
            echo " **** HasChildren ****";

            $childrenMenus = $category->getChildrenCategories();
            foreach ($childrenMenus as $id => $childrenMenu) {
                $html .= "<option value=\"" .  $childrenMenu->getId()  . "\"> -- " . $childrenMenu->getName() . "</option>";
            }
        }
        /*        else
                {
                    $html .= "<option value=\"" .  $category->getId()  . "\">" . strtoupper($category->getName()) . "</option>";
                }
        */
    }
    return $html;
}


function getCategoryNav()
{
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $categoryFactory = $objectManager->create('Magento\Catalog\Helper\Category');
    $categoryManager = $objectManager->create('Magento\Catalog\Model\CategoryRepository');
    $customerSession = $objectManager->get('Magento\Customer\Model\Session');
    $categoryId = 831;  //Parent Category ID
    $subCategory = $objectManager->create('Magento\Catalog\Model\Category')->load($categoryId);
    $categories = $subCategory->getChildrenCategories();
    $sideMenuId = 491;
    //$sideMenuId = 43;
    $sideMenuSubCategory = $objectManager->create('Magento\Catalog\Model\Category')->load($sideMenuId);
    $sideMenuCategories = $sideMenuSubCategory->getChildrenCategories();
    $html = '    <div class="categories">';
    foreach ($categories as $id => $category) {
        //echo '**** ' . $category->getId() . ' ****';
        if ($category->hasChildren()) {
            $html .= '<div class="category-item">';
            $html .= '  <a class="category-item-link has-children" id="dropdown-' . $category->getId() . '" href="#" />' . $category->getName() . ' <i class="fas fa-caret-down ml-1"></i></a>';
            $html .= '  <div class="category-sub-menu" aria-labelledby="dropdown-' . $category->getId() . '">';
            $childrenMenus = $category->getChildrenCategories();
            foreach ($childrenMenus as $id => $childrenMenu) {
                //echo '  #### ' . $childrenMenu->getName() . '####';
                $html .= '<div class="sub-link-container">';
                $html .= '<a class="category-item-sub-link" href="' . $childrenMenu->getUrl() . '">' . $childrenMenu->getName() . '</a>';
                $subSubCategories = $childrenMenu->getChildrenCategories();
                foreach($subSubCategories as $id => $subSubCategory) {
                    $html .= '<a class="category-item-sub-sub-link" href="' . $subSubCategory->getUrl() . '">' . $subSubCategory->getName() . '</a>';
                }
                $html .= '  <a href="' . $childrenMenu->getUrl() . '" class="category-item-sub-sub-link view-more">View all<i class="fas fa-chevron-right ml-2"></i></a></div>';
            }
            $html .= ' <a class="main-view-more" href="' . $category->getUrl() . '">View all '. $category->getName() .'<i class="fas fa-chevron-right ml-2"></i></a>';
            $html .= '    </div>';
            $html .= "</div>";
        } else {
            $html .= '<div class="category-item">';
            $html .= '  <a class="category-item-link" href="' . $category->getUrl() . '" />' . $category->getName() . '</a>';
            $html .= '</div>';
        }
    }
    $html .= '    </div>';
    return $html;
}
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');

?>

<div class="main-menu-container ">
    <div class="container">

        <div class="main-menu--left">

            <div class="category-menu-container desktop">

                <div class="category-menu desktop">
                    <!--                    <a class="top-navbar-link category-menu-toggle" href="/">Home</a>-->
                    <?php echo getCategoryNav() ?>
                </div>
            </div>

        </div>
        <div class="main-menu--right">
            <?php  echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('bottom_navbar_right')
                ->toHtml(); ?>
        </div>
    </div>
</div>


<div class="category-menu-mobile">
    <div class="category-menu-mobile-content">
        <?php echo getCategoryNav() ?>
    </div>
    <div>
        <div class="mobile-menu bg-light">
            <?php  echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('mobile_menu_bottom_nav')
                ->toHtml(); ?>
        </div>
    </div>
    <div class="category-menu-mobile-backdrop">
        <a href="#" class="mobile-menu-close"><i class="fas fa-times"></i></a>
    </div>
</div>
<script>
    require(['jquery'], function ($) {
        $('.nav-sections-item-content').removeClass();
    });

</script>
